"""Shared JSON schemas for system-logging-manager CLI and API system tests."""

EVENT_ITEM_SCHEMA: dict[str, object] = {
    "type": "object",
    "properties": {
        "RecID": {"type": "integer"},
        "EventID": {"type": "string"},
        "Category": {"type": "string"},
        "Severity": {"type": "string"},
        "Priority": {"type": "integer"},
        "CreatedAt": {"type": "string"},
        "Source": {"type": "string"},
        "EventRecID": {"type": "integer"},
        "Acknowledged": {"type": "boolean"},
        "AcknowledgedBy": {"type": "string"},
        "AcknowledgedAt": {"type": "string"},
        "Muted": {"type": "boolean"},
        "MutedBy": {"type": "string"},
        "MutedAt": {"type": "string"},
        "Status": {"type": "string"},
        "Message": {"type": "string"},
        "LastRecID": {"type": ["integer", "null"]},
        "LastEventID": {"type": ["string", "null"]},
        "LastEventRecID": {"type": ["integer", "null"]},
        "LastTimestamp": {"type": ["string", "null"]},
        "LastValueType": {"type": ["string", "null"]},
        "LastValueNum": {"type": ["number", "null"]},
        "LastValueText": {"type": ["string", "null"]},
        "LastValueBool": {"type": ["boolean", "null"]},
        "LastValueUnit": {"type": ["string", "null"]},
        "Meta": {
            "type": "object",
            "additionalProperties": {"type": "string"},
        },
    },
    "required": [
        "RecID",
        "EventID",
        "Category",
        "Severity",
        "Priority",
        "CreatedAt",
        "Source",
        "EventRecID",
        "Acknowledged",
        "AcknowledgedBy",
        "AcknowledgedAt",
        "Muted",
        "MutedBy",
        "MutedAt",
        "Status",
        "Message",
        "LastRecID",
        "LastEventID",
        "LastEventRecID",
        "LastTimestamp",
        "LastValueType",
        "LastValueNum",
        "LastValueText",
        "LastValueBool",
        "LastValueUnit",
    ],
}

EVENT_LIST_SCHEMA: dict[str, object] = {
    "type": "array",
    "items": EVENT_ITEM_SCHEMA,
}

OK_SCHEMA: dict[str, object] = {
    "type": "object",
    "properties": {"ok": {"type": "boolean"}},
    "required": ["ok"],
}
