[messaging]
url=tls://127.0.0.1:4222
client_name=network-metrics-cli
timeout=5s
ca=/etc/lite-nas/certificates/transport/root-ca.crt
cert=/etc/lite-nas/certificates/transport/lite-nas-network-metrics-cli/client.crt
key=/etc/lite-nas/certificates/transport/lite-nas-network-metrics-cli/client.key

[logging]
level=info
format=rfc5424
output=file
file_path=/var/log/lite-nas/network-metrics-cli.log
