[process_metrics]
enabled=true
poll_interval=5s

[messaging]
url=tls://127.0.0.1:4222
client_name=process-metrics
ca=/etc/lite-nas/certificates/transport/root-ca.crt
cert=/etc/lite-nas/certificates/transport/lite-nas-process-metrics/client.crt
key=/etc/lite-nas/certificates/transport/lite-nas-process-metrics/client.key
timeout=5s

[logging]
level=warn
format=rfc5424
output=file
file_path=/var/log/lite-nas/process-metrics.log
