[messaging]
url=tls://127.0.0.1:4222
client_name=rbac-service
ca=/etc/lite-nas/certificates/transport/root-ca.crt
cert=/etc/lite-nas/certificates/transport/lite-nas-rbac-service/client.crt
key=/etc/lite-nas/certificates/transport/lite-nas-rbac-service/client.key
timeout=5s

[logging]
level=warn
format=rfc5424
output=file
file_path=/var/log/lite-nas/rbac-service.log

[cache]
invalidate_interval=1h
real_user_ttl=24h
non_interactive_user_ttl=168h
