[rules]
files=/etc/lite-nas/resources-monitor/rules/system-metrics.json,/etc/lite-nas/resources-monitor/rules/network-metrics.json,/etc/lite-nas/resources-monitor/rules/zfs-metrics.json

[messaging]
url=tls://127.0.0.1:4222
client_name=resources-monitor
ca=/etc/lite-nas/certificates/transport/root-ca.crt
cert=/etc/lite-nas/certificates/transport/lite-nas-resources-monitor/client.crt
key=/etc/lite-nas/certificates/transport/lite-nas-resources-monitor/client.key
timeout=5s

[auth]
ca=/etc/lite-nas/certificates/identities/root-ca.crt
cert=/etc/lite-nas/certificates/identities/lite-nas-resources-monitor/client.crt
key=/etc/lite-nas/certificates/identities/lite-nas-resources-monitor/client.key
service_name=resources-monitor
service_login=lite-nas-resources-monitor

[logging]
level=warn
format=rfc5424
output=file
file_path=/var/log/lite-nas/resources-monitor.log
