[messaging]
url=tls://127.0.0.1:4222
client_name=security-email-notifier
ca=/etc/lite-nas/certificates/transport/root-ca.crt
cert=/etc/lite-nas/certificates/transport/lite-nas-sec-email-notifier/client.crt
key=/etc/lite-nas/certificates/transport/lite-nas-sec-email-notifier/client.key
timeout=5s

[logging]
level=warn
format=rfc5424
output=file
file_path=/var/log/lite-nas/security-email-notifier.log
