[messaging]
url=tls://127.0.0.1:4222
client_name=security-logging-manager
ca=/etc/lite-nas/certificates/transport/root-ca.crt
cert=/etc/lite-nas/certificates/transport/lite-nas-sec-log-mgr/client.crt
key=/etc/lite-nas/certificates/transport/lite-nas-sec-log-mgr/client.key
timeout=5s

[auth_tokens]
issuer=lite-nas-auth
audience=lite-nas-management-api
access_lifetime=15m
clock_skew=30s
verification_cert=/etc/lite-nas/certificates/auth/token-signing.crt
enforce_refresh_client_ip=false

[loggingmanager]
sqlite_path=/var/lib/lite-nas/security-logging-manager/log.db
max_events=200
max_occurrences=250000
event_id_prefix=securevent

[loggingmanager_writer]
batch_size=100
flush_interval=100ms

[loggingmanager_cleanup]
batch_size=5000
interval=5s

[logging]
level=warn
format=rfc5424
output=file
file_path=/var/log/lite-nas/security-logging-manager.log
