[messaging]
url=tls://127.0.0.1:4222
client_name=security-logging-manager-cli
ca=/etc/lite-nas/certificates/transport/root-ca.crt
cert=/etc/lite-nas/certificates/transport/lite-nas-security-logging-manager-cli/client.crt
key=/etc/lite-nas/certificates/transport/lite-nas-security-logging-manager-cli/client.key
timeout=5s

[logging]
level=warn
format=rfc5424
output=file
file_path=/var/log/lite-nas/security-logging-manager-cli.log
