[messaging]
url=tls://127.0.0.1:4222
client_name=system-email-notifier
ca=/etc/lite-nas/certificates/transport/root-ca.crt
cert=/etc/lite-nas/certificates/transport/lite-nas-sys-email-notifier/client.crt
key=/etc/lite-nas/certificates/transport/lite-nas-sys-email-notifier/client.key
timeout=5s

[email]
to=
cc=
from=security-alert-notifier@lite-nas.com
subject_prefix=[LiteNAS]

[smtp]
host=127.0.0.1
port=25
timeout=10s
helo=localhost

[logging]
level=warn
format=rfc5424
output=file
file_path=/var/log/lite-nas/system-email-notifier.log
