[messaging]
url=tls://127.0.0.1:4222
client_name=system-logging-manager
ca=/etc/lite-nas/certificates/transport/root-ca.crt
cert=/etc/lite-nas/certificates/transport/lite-nas-sys-log-mgr/client.crt
key=/etc/lite-nas/certificates/transport/lite-nas-sys-log-mgr/client.key
timeout=5s

[loggingmanager]
sqlite_path=/var/lib/lite-nas/system-logging-manager/log.db
max_events=500
max_occurrences=50000
event_id_prefix=event

[loggingmanager_writer]
batch_size=100
flush_interval=100ms

[loggingmanager_cleanup]
batch_size=5000
interval=5s

[logging]
level=warn
format=rfc5424
output=file
file_path=/var/log/lite-nas/system-logging-manager.log
