[messaging]
url=tls://127.0.0.1:4222
client_name=system-logging-manager-cli
ca=/etc/lite-nas/certificates/transport/root-ca.crt
cert=/etc/lite-nas/certificates/transport/lite-nas-sys-log-mgr-cli/client.crt
key=/etc/lite-nas/certificates/transport/lite-nas-sys-log-mgr-cli/client.key
timeout=5s

[auth]
ca=/etc/lite-nas/certificates/identities/root-ca.crt
cert=/etc/lite-nas/certificates/identities/lite-nas-sys-log-mgr-cli/client.crt
key=/etc/lite-nas/certificates/identities/lite-nas-sys-log-mgr-cli/client.key
service_name=system-logging-manager-cli
service_login=lite-nas-sys-log-mgr-cli

[logging]
level=warn
format=rfc5424
output=file
file_path=/var/log/lite-nas/system-logging-manager-cli.log
