[messaging]
url=nats://127.0.0.1:4222
client_name=system-metrics-cli
timeout=5s
ca=/etc/lite-nas/certificates/root-ca.crt
cert=/etc/lite-nas/certificates/lite-nas-system-metrics-cli/client.crt
key=/etc/lite-nas/certificates/lite-nas-system-metrics-cli/client.key

[logging]
level=info
format=rfc5424
output=stderr
