[metrics]
poll_interval=1s
history_size=120

[messaging]
url=tls://127.0.0.1:4222
client_name=system-metrics
ca=/etc/lite-nas/certificates/transport/root-ca.crt
cert=/etc/lite-nas/certificates/transport/lite-nas-system-metrics/client.crt
key=/etc/lite-nas/certificates/transport/lite-nas-system-metrics/client.key
timeout=5s

[logging]
level=warn
format=rfc5424
output=file
file_path=/var/lib/lite-nas/system-metrics.log
