[metrics]
poll_interval=5s
zpool_path=/sbin/zpool
history_size=120

[messaging]
url=tls://127.0.0.1:4222
client_name=zfs-metrics
ca=/etc/lite-nas/certificates/transport/root-ca.crt
cert=/etc/lite-nas/certificates/transport/lite-nas-zfs-metrics/client.crt
key=/etc/lite-nas/certificates/transport/lite-nas-zfs-metrics/client.key
timeout=5s

[logging]
level=warn
format=rfc5424
output=file
file_path=/var/log/lite-nas/zfs-metrics.log
