#!/bin/sh
set -e

# shellcheck disable=SC1091
. /usr/share/debconf/confmodule

db_input high lite-nas/gpl-notice || true
db_go || true

db_input high lite-nas/profile-transform-note || true
db_go || true

db_input high lite-nas/replace-nats-config || true
db_go || true
db_get lite-nas/replace-nats-config || true

if [ "$RET" = "false" ]; then
	db_input high lite-nas/manual-nats-config-note || true
	db_go || true
fi

exit 0
