#!/bin/sh
set -e

# shellcheck disable=SC1091
. /usr/share/debconf/confmodule

if command -v debconf-set-selections >/dev/null 2>&1; then
	printf '%s\n' \
		'postfix postfix/main_mailer_type select Local only' \
		'postfix postfix/mailname string localhost' | debconf-set-selections
fi

db_input high lite-nas/gpl-notice || true
db_go || true

db_input high lite-nas/profile-transform-note || true
db_go || true

db_input high lite-nas/replace-nats-config || true
db_go || true
db_get lite-nas/replace-nats-config || true

if [ "$RET" = "false" ]; then
	db_input high lite-nas/manual-nats-config-note || true
	db_go || true
fi

exit 0
