#!/bin/sh
set -e

case "$1" in
purge)
	if [ -x /usr/share/debconf/confmodule ]; then
		# shellcheck disable=SC1091
		. /usr/share/debconf/confmodule
		db_purge || true
	fi
	;;
remove | upgrade | failed-upgrade | disappear)
	;;
*)
	echo "postrm called with unsupported argument: $1" >&2
	exit 1
	;;
esac

exit 0
