[metrics]
poll_interval=1s
history_size=120

[messaging]
url=tls://127.0.0.1:4222
client_name=system-metrics
ca=/etc/liteNAS/certificates/root-ca.crt
cert=/etc/liteNAS/certificates/lite-nas-system-metrics/client.crt
key=/etc/liteNAS/certificates/lite-nas-system-metrics/client.key
timeout=5s

[logging]
level=info
format=rfc5424
output=file
file_path=/var/log/liteNAS/system-metrics.log
