[http]
address=127.0.0.1:9090

[messaging]
url=tls://127.0.0.1:4222
client_name=web-gateway
ca=/etc/liteNAS/certificates/root-ca.crt
cert=/etc/liteNAS/certificates/lite-nas-web-gateway/client.crt
key=/etc/liteNAS/certificates/lite-nas-web-gateway/client.key
timeout=5s

[logging]
level=info
format=rfc5424
output=file
file_path=/var/log/liteNAS/web-gateway.log
