authorization {
  users: [
    {
      user: "lite-nas-system-metrics"
      permissions: {
        publish: ["system.metrics.events.stats", "_INBOX.>"]
        subscribe: ["system.metrics.rpc.stats.get", "system.metrics.rpc.history.get"]
      }
    }
    {
      user: "lite-nas-system-metrics-cli"
      permissions: {
        publish: ["system.metrics.rpc.stats.get", "system.metrics.rpc.history.get"]
        subscribe: ["_INBOX.>"]
      }
    }
    {
      user: "lite-nas-web-gateway"
      permissions: {
        publish: ["system.metrics.rpc.stats.get", "system.metrics.rpc.history.get"]
        subscribe: ["_INBOX.>"]
      }
    }
  ]
}
