tls {
  cert_file: "/etc/nats-server/certificates/server.crt"
  key_file: "/etc/nats-server/certificates/server.key"
  ca_file: "/etc/nats-server/certificates/root-ca.crt"
  verify: true
  verify_and_map: true
}
