import type { NetworkMetricSnapshotDTO } from "@dto/monitoring/network-metric";
import { buildNetworkInterfacePanelItems } from "@helpers/network-metric-panel";

const networkMetricItems: NetworkMetricSnapshotDTO[] = [
  {
    interfaces: [
      {
        adapter: {
          description: "Ethernet Controller",
          device_id: "15fb",
          device_name: "I219-LM",
          vendor_id: "8086",
          vendor_name: "Intel",
        },
        address: "00:11:22:33:44:55",
        duplex: "full",
        kind: "ethernet",
        mtu: 1500,
        name: "eth0",
        oper_state: "up",
        speed_mbps: 1000,
        statistics: {
          rx_bytes: 100,
          rx_compressed: 0,
          rx_crc_errors: 0,
          rx_dropped: 0,
          rx_errors: 0,
          rx_fifo_errors: 0,
          rx_frame_errors: 0,
          rx_length_errors: 0,
          rx_missed_errors: 0,
          rx_multicast: 0,
          rx_nohandler: 0,
          rx_over_errors: 0,
          rx_packets: 2,
          tx_aborted_errors: 0,
          tx_bytes: 150,
          tx_carrier_errors: 0,
          tx_collisions: 0,
          tx_compressed: 0,
          tx_dropped: 0,
          tx_errors: 0,
          tx_fifo_errors: 0,
          tx_heartbeat_errors: 0,
          tx_packets: 4,
          tx_window_errors: 0,
        },
      },
    ],
    kernel_pressure: {
      softirqs: {
        net_rx_per_cpu: [10, 20],
        net_rx_total: 30,
        net_tx_per_cpu: [5, 15],
        net_tx_total: 20,
      },
    },
    protocols: {
      icmp: {},
      ip: {},
      ip_ext: {},
      tcp: { ActiveOpens: 3 },
      tcp_ext: {},
      udp: { InDatagrams: 5 },
      udplite: {},
    },
    sockets: {
      by_state: { LISTEN: 1 },
      sockstat: {
        frag_inuse: 0,
        frag_memory: 0,
        raw_inuse: 0,
        sockets_used: 6,
        tcp_alloc: 2,
        tcp_inuse: 2,
        tcp_mem: 1,
        tcp_orphan: 0,
        tcp_time_wait: 0,
        udp_inuse: 1,
        udp_mem: 1,
        udplite_inuse: 0,
      },
      top_local_ports: [],
      top_remote_ips: [],
      total: {
        all: 6,
        tcp: 2,
        tcp6: 0,
        udp: 1,
        udp6: 0,
      },
    },
    timestamp: "2026-06-15T13:00:00Z",
  },
  {
    interfaces: [
      {
        adapter: {
          description: "Ethernet Controller",
          device_id: "15fb",
          device_name: "I219-LM",
          vendor_id: "8086",
          vendor_name: "Intel",
        },
        address: "00:11:22:33:44:55",
        duplex: "full",
        kind: "ethernet",
        mtu: 1500,
        name: "eth0",
        oper_state: "up",
        speed_mbps: 1000,
        statistics: {
          rx_bytes: 140,
          rx_compressed: 0,
          rx_crc_errors: 1,
          rx_dropped: 1,
          rx_errors: 1,
          rx_fifo_errors: 0,
          rx_frame_errors: 0,
          rx_length_errors: 0,
          rx_missed_errors: 0,
          rx_multicast: 0,
          rx_nohandler: 0,
          rx_over_errors: 0,
          rx_packets: 3,
          tx_aborted_errors: 0,
          tx_bytes: 190,
          tx_carrier_errors: 0,
          tx_collisions: 0,
          tx_compressed: 0,
          tx_dropped: 1,
          tx_errors: 1,
          tx_fifo_errors: 0,
          tx_heartbeat_errors: 0,
          tx_packets: 5,
          tx_window_errors: 0,
        },
      },
      {
        address: "66:77:88:99:AA:BB",
        duplex: "full",
        kind: "ethernet",
        name: "eth1",
        oper_state: "down",
        statistics: {
          rx_bytes: 60,
          rx_compressed: 0,
          rx_crc_errors: 0,
          rx_dropped: 0,
          rx_errors: 0,
          rx_fifo_errors: 0,
          rx_frame_errors: 0,
          rx_length_errors: 0,
          rx_missed_errors: 0,
          rx_multicast: 0,
          rx_nohandler: 0,
          rx_over_errors: 0,
          rx_packets: 1,
          tx_aborted_errors: 0,
          tx_bytes: 80,
          tx_carrier_errors: 0,
          tx_collisions: 0,
          tx_compressed: 0,
          tx_dropped: 0,
          tx_errors: 0,
          tx_fifo_errors: 0,
          tx_heartbeat_errors: 0,
          tx_packets: 2,
          tx_window_errors: 0,
        },
      },
    ],
    kernel_pressure: {
      softirqs: {
        net_rx_per_cpu: [25, 35],
        net_rx_total: 60,
        net_tx_per_cpu: [20, 30],
        net_tx_total: 50,
      },
    },
    protocols: {
      icmp: {},
      ip: {},
      ip_ext: {},
      tcp: { ActiveOpens: 4 },
      tcp_ext: {},
      udp: { InDatagrams: 9 },
      udplite: {},
    },
    sockets: {
      by_state: { ESTABLISHED: 2, LISTEN: 1 },
      sockstat: {
        frag_inuse: 0,
        frag_memory: 0,
        raw_inuse: 0,
        sockets_used: 8,
        tcp_alloc: 3,
        tcp_inuse: 3,
        tcp_mem: 1,
        tcp_orphan: 0,
        tcp_time_wait: 0,
        udp_inuse: 2,
        udp_mem: 1,
        udplite_inuse: 0,
      },
      top_local_ports: [],
      top_remote_ips: [],
      total: {
        all: 8,
        tcp: 3,
        tcp6: 0,
        udp: 2,
        udp6: 0,
      },
    },
    timestamp: "2026-06-15T13:00:01Z",
  },
];

const expectedInterfaceCards = [
  {
    adapterLabel: "Intel I219-LM",
    errorAndDropSeries: {
      stamps: ["2026-06-15T13:00:00Z", "2026-06-15T13:00:01Z"],
      valuesByKey: {
        "RX errors+drops": [0, 2],
        "TX errors+drops": [0, 2],
      },
    },
    linkDetailsLabel: "ethernet | 1,000 Mbps | full | MTU 1,500",
    name: "eth0",
    packetRateSeries: {
      stamps: ["2026-06-15T13:00:00Z", "2026-06-15T13:00:01Z"],
      valuesByKey: {
        "RX packets": [0, 1],
        "TX packets": [0, 1],
      },
    },
    status: "up",
    throughputSeries: {
      stamps: ["2026-06-15T13:00:00Z", "2026-06-15T13:00:01Z"],
      valuesByKey: {
        RX: [0, 40],
        TX: [0, 40],
      },
    },
    totalsLabels: [
      { key: "Total RX", value: "140 B" },
      { key: "Total TX", value: "190 B" },
    ],
  },
  {
    adapterLabel: "Adapter details unavailable",
    errorAndDropSeries: {
      stamps: ["2026-06-15T13:00:00Z", "2026-06-15T13:00:01Z"],
      valuesByKey: {
        "RX errors+drops": [0, 0],
        "TX errors+drops": [0, 0],
      },
    },
    linkDetailsLabel: "ethernet | full",
    name: "eth1",
    packetRateSeries: {
      stamps: ["2026-06-15T13:00:00Z", "2026-06-15T13:00:01Z"],
      valuesByKey: {
        "RX packets": [0, 0],
        "TX packets": [0, 0],
      },
    },
    status: "down",
    throughputSeries: {
      stamps: ["2026-06-15T13:00:00Z", "2026-06-15T13:00:01Z"],
      valuesByKey: {
        RX: [0, 0],
        TX: [0, 0],
      },
    },
    totalsLabels: [
      { key: "Total RX", value: "60 B" },
      { key: "Total TX", value: "80 B" },
    ],
  },
];

test("builds latest interface cards with adapter labels, link details, totals, and chart series", () => {
  expect(buildNetworkInterfacePanelItems([...networkMetricItems])).toEqual(expectedInterfaceCards);
});
